const mongoose = require("mongoose")
const Product = require("../models/Product.model")
const { ObjectId } = mongoose.Types

const MONGO_URI = process.env.MONGODB_URI || "mongodb://127.0.0.1:27017/third-wheel"

const products = [
  {
    title: "Specialized Turbo Creo SL Expert Carbon",
    brand: "Specialized",
    model: "Turbo Creo SL Expert Carbon",
    year: 2021,
    description: "The Specialized Turbo Creo SL Expert Carbon is a lightweight and high-performance electric road bike designed for long-distance rides and endurance training.",
    price: 8799,
    image: ["https://bikefair.ams3.cdn.digitaloceanspaces.com/public/337396/responsive-images/ped027_01___media_library_original_510_360.jpg"],
    condition: "As good as new",
    isSold: false,
    specifications: {
      frameSize: "Large",
      motorType: "Specialized SL 1.1, custom lightweight motor",
      batteryCapacity: "320Wh",
      wheelsSize: "700c",
      maxSpeed: "28mph",
      range: "up to 80 miles",
      gears: "Shimano Ultegra Di2 11-speed",
    },
    postedBy: new ObjectId("64158f4ba0a74e8d648ff1c0"),
  },
  {
    title: "Cannondale Moterra Neo 5",
    brand: "Cannondale",
    model: "Moterra Neo 5",
    year: 2022,
    description: "The Cannondale Moterra Neo 5 is a versatile and powerful electric mountain bike designed for all-mountain and trail riding.",
    price: 4799,
    image: ["https://bikefair.ams3.cdn.digitaloceanspaces.com/public/337396/responsive-images/ped027_01___media_library_original_510_360.jpg"],
    condition: "Used",
    isSold: false,
    specifications: {
      frameSize: "Medium",
      motorType: "Bosch Performance CX 250W",
      batteryCapacity: "625Wh",
      wheelsSize: "27.5+",
      maxSpeed: "20mph",
      range: "up to 75 miles",
      gears: "Shimano Deore M5100 11-speed",
    },
    postedBy: new ObjectId("64158f4ba0a74e8d648ff1c0"),
  },
  {
    title: "Trek Rail 9.9",
    brand: "Trek",
    model: "Rail 9.9",
    year: 2022,
    description: "The Trek Rail 9.9 is a high-end electric mountain bike designed for aggressive trail riding and enduro racing.",
    price: 11999,
    image: ["https://bikefair.ams3.cdn.digitaloceanspaces.com/public/337396/responsive-images/ped027_01___media_library_original_510_360.jpg"],
    condition: "Poor condition",
    isSold: false,
    specifications: {
      frameSize: "Large",
      motorType: "Bosch Performance Line CX",
      batteryCapacity: "625Wh",
      wheelsSize: '29"',
      maxSpeed: "20mph",
      range: "up to 70 miles",
      gears: "SRAM X01 Eagle 12-speed",
    },
    postedBy: new ObjectId("64158f4ba0a74e8d648ff1c0"),
  },
  {
    title: "Giant Road E+ Pro 1",
    brand: "Giant",
    model: "Road E+ Pro 1",
    year: 2022,
    description: "The Giant Road E+ Pro 1 is an electric road bike designed for speed and performance, with a powerful motor and responsive handling.",
    price: 5999,
    image: ["https://bikefair.ams3.cdn.digitaloceanspaces.com/public/337396/responsive-images/ped027_01___media_library_original_510_360.jpg"],
    condition: "New",
    isSold: false,
    specifications: {
      frameSize: "Medium",
      motorType: "Giant SyncDrive Pro",
      batteryCapacity: "375Wh",
      wheelsSize: "700c",
      maxSpeed: "28mph",
      range: "up to 60 miles",
      gears: "Shimano Ultegra Di2 11-speed",
    },
    postedBy: new ObjectId("64158f4ba0a74e8d648ff1c0"),
  },
  {
    title: "Giant Talon 29er",
    brand: "Giant",
    model: "Talon",
    year: 2017,
    description: "The Giant Talon 29er is a hardtail mountain bike designed for trail riding.",
    price: 499,
    image: ["https://bikefair.ams3.cdn.digitaloceanspaces.com/public/337396/responsive-images/ped027_01___media_library_original_510_360.jpg"],
    condition: "Poor condition",
    isSold: false,
    specifications: {
      frameSize: "Medium",
      motorType: null,
      batteryCapacity: null,
      wheelsSize: "29-inch",
      maxSpeed: null,
      range: null,
      gears: "Shimano Deore 3x9",
    },
    postedBy: new ObjectId("64158f4ba0a74e8d648ff1c0"),
  },
  {
    title: "Specialized Turbo Levo Comp",
    brand: "Specialized",
    model: "Turbo Levo Comp",
    year: 2022,
    description: "The Specialized Turbo Levo Comp is a full-suspension electric mountain bike designed for all-mountain riding, with a powerful motor and advanced suspension system.",
    price: 7999,
    image: ["https://bikefair.ams3.cdn.digitaloceanspaces.com/public/337396/responsive-images/ped027_01___media_library_original_510_360.jpg"],
    condition: "As good as new",
    isSold: false,
    specifications: {
      frameSize: "Medium",
      motorType: "Specialized 2.2",
      batteryCapacity: "700Wh",
      wheelsSize: '27.5"',
      maxSpeed: "20mph",
      range: "up to 70 miles",
      gears: "SRAM NX Eagle 12-speed",
    },
    postedBy: new ObjectId("64158f4ba0a74e8d648ff1c0"),
  },
  {
    title: "Specialized Turbo Vado SL 4.0 EQ",
    brand: "Specialized",
    model: "Turbo Vado SL 4.0 EQ",
    year: 2021,
    description: "The Specialized Turbo Vado SL 4.0 EQ is a high-performance electric bike designed for commuting and fitness riding.",
    price: 3999,
    image: ["https://bikefair.ams3.cdn.digitaloceanspaces.com/public/337396/responsive-images/ped027_01___media_library_original_510_360.jpg"],
    condition: "As good as new",
    isSold: false,
    specifications: {
      frameSize: "Medium",
      motorType: "Specialized SL 1.1, custom lightweight motor",
      batteryCapacity: "320Wh",
      wheelsSize: "700c",
      maxSpeed: "28mph",
      range: "up to 80 miles",
      gears: "Shimano Deore 10-speed",
    },
    postedBy: new ObjectId("64158f4ba0a74e8d648ff1c0"),
  },
  {
    title: "Cannondale Topstone Neo Carbon Lefty 1",
    brand: "Cannondale",
    model: "Topstone Neo Carbon Lefty 1",
    year: 2022,
    description: "The Cannondale Topstone Neo Carbon Lefty 1 is an electric gravel bike designed for adventure riding, with a lightweight carbon frame and a unique Lefty suspension fork.",
    price: 7999,
    image: ["https://bikefair.ams3.cdn.digitaloceanspaces.com/public/337396/responsive-images/ped027_01___media_library_original_510_360.jpg"],
    condition: "Used",
    isSold: false,
    specifications: {
      frameSize: "Large",
      motorType: "Mahle ebikemotion X35",
      batteryCapacity: "500Wh",
      wheelsSize: "700c",
      maxSpeed: "20mph",
      range: "up to 60 miles",
      gears: "Shimano GRX 1x11-speed",
    },
    postedBy: new ObjectId("64158f4ba0a74e8d648ff1c0"),
  },
  {
    title: "Trek Powerfly FS 9 LT",
    brand: "Trek",
    model: "Powerfly FS 9 LT",
    year: 2022,
    description: "This electric mountain bike is designed to give you the power to ride more trails. It features a full suspension setup and a powerful Bosch Performance CX motor.",
    price: 8000,
    image: ["https://bikefair.ams3.cdn.digitaloceanspaces.com/public/337396/responsive-images/ped027_01___media_library_original_510_360.jpg"],
    condition: "New",
    isSold: false,
    specifications: {
      frameSize: "Medium",
      motorType: "Bosch Performance CX",
      batteryCapacity: "625 Wh",
      wheelsSize: "29 inches",
      maxSpeed: "20 mph",
      range: "Up to 75 miles",
      gears: "12-speed Shimano XT",
    },
    postedBy: new ObjectId("64158f4ba0a74e8d648ff1c0"),
  },
  {
    title: "Specialized Turbo Levo",
    brand: "Specialized",
    model: "Turbo Levo",
    year: 2021,
    description: "This electric mountain bike is designed to give you the power to ride more trails. It features a full suspension setup and a powerful Brose motor.",
    price: 7000,
    image: ["https://bikefair.ams3.cdn.digitaloceanspaces.com/public/337396/responsive-images/ped027_01___media_library_original_510_360.jpg"],
    condition: "As good as new",
    isSold: false,
    specifications: {
      frameSize: "Large",
      motorType: "Brose",
      batteryCapacity: "700 Wh",
      wheelsSize: "27.5 inches",
      maxSpeed: "20 mph",
      range: "Up to 60 miles",
      gears: "11-speed Shimano XT",
    },
    postedBy: new ObjectId("64158f4ba0a74e8d648ff1c0"),
  },
  {
    title: "Specialized Turbo Levo",
    brand: "Specialized",
    model: "Turbo Levo",
    year: 2022,
    description: "The Turbo Levo is a fully-fledged progressive trail bike.",
    price: 5499,
    image: ["https://bikefair.ams3.cdn.digitaloceanspaces.com/public/337396/responsive-images/ped027_01___media_library_original_510_360.jpg"],
    condition: "New",
    isSold: false,
    specifications: {
      frameSize: "Large",
      motorType: "Brose",
      batteryCapacity: "700Wh",
      wheelsSize: '29"',
      maxSpeed: "25km/h",
      range: "80km",
      gears: "12",
    },
    postedBy: new ObjectId("64158f4ba0a74e8d648ff1c0"),
  },
  {
    title: "Trek Powerfly FS 9",
    brand: "Trek",
    model: "Powerfly FS 9",
    year: 2021,
    description: "The Powerfly FS 9 is a top-of-the-line full suspension electric mountain bike.",
    price: 7899,
    image: ["https://bikefair.ams3.cdn.digitaloceanspaces.com/public/337396/responsive-images/ped027_01___media_library_original_510_360.jpg"],
    condition: "As good as new",
    isSold: false,
    specifications: {
      frameSize: "Medium",
      motorType: "Bosch Performance CX",
      batteryCapacity: "625Wh",
      wheelsSize: '27.5"',
      maxSpeed: "25km/h",
      range: "75km",
      gears: "12",
    },
    postedBy: new ObjectId("64158f4ba0a74e8d648ff1c0"),
  },
  {
    title: "E-speeder 5",
    brand: "Tryke",
    model: "Model A",
    year: 2022,
    description: "This is a brand new electric bike with top of the line features.",
    price: 2000,
    image: ["https://bikefair.ams3.cdn.digitaloceanspaces.com/public/337396/responsive-images/ped027_01___media_library_original_510_360.jpg"],
    condition: "New",
    isSold: false,
    specifications: {
      frameSize: "Medium",
      motorType: "Hub Motor",
      batteryCapacity: "500W",
      wheelsSize: "26 inches",
      maxSpeed: "20 mph",
      range: "40 miles",
      gears: "6 Speed",
    },
    postedBy: new ObjectId("64158f4ba0a74e8d648ff1c0"),
  },
  {
    title: "E-speeder 5",
    brand: "Tryke",
    model: "Model B",
    year: 2021,
    description: "This is a used electric bike in excellent condition.",
    price: 1500,
    image: ["https://bikefair.ams3.cdn.digitaloceanspaces.com/public/337396/responsive-images/ped027_01___media_library_original_510_360.jpg"],
    condition: "As good as new",
    isSold: false,
    specifications: {
      frameSize: "Large",
      motorType: "Mid Drive",
      batteryCapacity: "750W",
      wheelsSize: "27.5 inches",
      maxSpeed: "25 mph",
      range: "50 miles",
      gears: "10 Speed",
    },
    postedBy: new ObjectId("64158f4ba0a74e8d648ff1c0"),
  },
  {
    title: "Xenon Exos",
    brand: "Xenon",
    model: "Exos",
    year: 2022,
    description: "This is a brand new electric bike with top of the line features.",
    price: 2150,
    image: ["https://bikefair.ams3.cdn.digitaloceanspaces.com/public/337396/responsive-images/ped027_01___media_library_original_510_360.jpg"],
    condition: "New",
    isSold: false,
    specifications: {
      frameSize: "Medium",
      motorType: "Hub Motor",
      batteryCapacity: "750W",
      wheelsSize: "28 inches",
      maxSpeed: "20 mph",
      range: "40 miles",
      gears: "7 Speed",
    },
    postedBy: new ObjectId("64158f4ba0a74e8d648ff1c0"),
  },
  {
    title: "Omega Zephyr",
    brand: "Omega",
    model: "Zephyr",
    year: 2021,
    description: "This is a used electric bike in excellent condition.",
    price: 1850,
    image: ["https://bikefair.ams3.cdn.digitaloceanspaces.com/public/337396/responsive-images/ped027_01___media_library_original_510_360.jpg"],
    condition: "As good as new",
    isSold: false,
    specifications: {
      frameSize: "Large",
      motorType: "Mid Drive",
      batteryCapacity: "500W",
      wheelsSize: "26 inches",
      maxSpeed: "25 mph",
      range: "50 miles",
      gears: "10 Speed",
    },
    postedBy: new ObjectId("64158f4ba0a74e8d648ff1c0"),
  },
  {
    title: "Eco-Cruise E200",
    brand: "Eco-Cruise",
    model: "E200",
    year: 2023,
    description: "This is a brand new electric bike with top of the line features.",
    price: 2250,
    image: ["https://bikefair.ams3.cdn.digitaloceanspaces.com/public/337396/responsive-images/ped027_01___media_library_original_510_360.jpg"],
    condition: "New",
    isSold: false,
    specifications: {
      frameSize: "Medium",
      motorType: "Mid Drive",
      batteryCapacity: "750W",
      wheelsSize: "28 inches",
      maxSpeed: "20 mph",
      range: "45 miles",
      gears: "8 Speed",
    },
    postedBy: new ObjectId("64158f4ba0a74e8d648ff1c0"),
  },
  {
    title: "Velocity Pro",
    brand: "Velocity",
    model: "Pro",
    year: 2021,
    description: "This is a used electric bike in excellent condition.",
    price: 1900,
    image: ["https://bikefair.ams3.cdn.digitaloceanspaces.com/public/337396/responsive-images/ped027_01___media_library_original_510_360.jpg"],
    condition: "As good as new",
    isSold: false,
    specifications: {
      frameSize: "Large",
      motorType: "Hub Motor",
      batteryCapacity: "500W",
      wheelsSize: "27.5 inches",
      maxSpeed: "25 mph",
      range: "50 miles",
      gears: "10 Speed",
    },
    postedBy: new ObjectId("64158f4ba0a74e8d648ff1c0"),
  },
]

mongoose
  .connect(MONGO_URI)
  .then((x) => {
    console.log(`Connected to Mongo database: "${x.connections[0].name}"`)

    return Product.create(products)
  })
  .then((productsFromDB) => {
    console.log(`Created ${productsFromDB.length} prdocuts`)

    return mongoose.connection.close()
  })
  .then(() => {
    console.log("DB connection closed!")
  })
  .catch((error) => console.log("An error ocurred: ", error))
